hydra:
  job:
    chdir: False  # This is used to fix problem with changind working directory that affects path problem

data:
  input:
    interactions: 
      path: tests/dataset_example.csv
      read_params:
        sep: ','
        encoding:
      column_params:
        user_id: user_id
        item_id: item_id
        weight: weight
        datetime: datetime
  output:
    model_path: tmp/model.pkl
    dataset_path: tmp/dataset.pkl
    recommendations_path: tmp/recommendations.csv
    metric_path: tmp/metrics.json
train_params:
  model_type: SVD
splitter_params:
    test_fold_frac: 0.1
    n_splits: 1
    random_state: 23
    filter_cold_users: False
    filter_cold_items: False
    filter_already_seen: False
metric_params:
  Recall:
    k: 10
  Precision:
    k: 10
predict_params:
  k: 10
  filter_viewed: False
  add_rank_col: False
s3_params:
  bucket_name: alex-werben-recsys-bucket