hydra:
  job:
    chdir: False  # This is used to fix problem with changind working directory that affects path problem
data:
  input:
    interactions_path: data/raw/BX-Book-Ratings.csv
    user_features_path: data/raw/BX-Users.csv
    item_features_path: data/raw/BX-Books.csv
  output:
    model_path: models/model.pkl
    metric_path: models/metrics.json
train_params:
  model_type: SVD
