name: Python package CI

on:
  push:
    branches:
      - '**'  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        poetry config virtualenvs.in-project true


    - name: Install Dependencies
      run: |
        poetry install
        poetry shell
        echo 
  
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --exclude .venv --count --select=E9,F63,F7,F82 --show-source
        # check code-style
        flake8 --exclude .venv --ignore=Q000,D100,E402,I201,I100,D104 --max-line-length=127 --count --exit-zero

    - name: Test with pytest
      run: |
        python pytest
    